const CONFIG = {
  CANVAS_W: 800,
  CANVAS_H: 800,

  COLS: 15,
  ROWS: 15,

  PLAYER_SPEED: 3,
  PLAYER_RADIUS: 6,

  TIME_LIMIT_BASE: 120,

  BLACKOUT_INTERVAL_BASE: 12000,
  BLACKOUT_DURATION_BASE: 4000,
  FLASHLIGHT_RADIUS_BASE: 100,
  BLACKOUT_FADE_SPEED: 0.06,

  SHIFT_INTERVAL_BASE: 18000,
  SHIFT_WALL_COUNT_BASE: 8,

  LEVEL_DIFFICULTY_SCALE: 0.12,

  PARTICLE_COUNT: 3,
  PARTICLE_LIFE: 60,

  COLORS: {
    CYAN: "#00fff2",
    MAGENTA: "#ff00e5",
    YELLOW: "#f5ff00",
    GREEN: "#39ff14",
    PINK: "#ff2d7b",
    RED: "#ff1744",
    BG: "#0a0a0f",
    WALL: "#1a1a2e",
    WALL_GLOW: "#0ff3",
    GRID: "#111122",
  },
};

CONFIG.CELL_W = Math.floor(CONFIG.CANVAS_W / CONFIG.COLS);
CONFIG.CELL_H = Math.floor(CONFIG.CANVAS_H / CONFIG.ROWS);
